services:
  - type: web
    name: futbol-api
    env: dotnet
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/Futbol.Api.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: Jwt__Key
        value: q7xe7+ekXfqEps7GRJeBw7yApqo8WZLKNttuC2Kr1Rv/Xq3J5FbD/w9JSxdYUK0j12FHORhzyQhi17CvXM4/Xg==
      - key: Jwt__Issuer
        value: Futbol.Api
      - key: Jwt__Audience
        value: Futbol.Web
      - key: Jwt__ExpiresMinutes
        value: "4320"
      - key: Cors__AllowedOrigins__0
        value: http://localhost:3000
      - key: Cors__AllowedOrigins__1
        value: https://statsfutbolpro.vercel.app
      - key: Cors__AllowedOrigins__2
        value: https://futbol-saas-posta.vercel.app
      - key: ConnectionStrings__DefaultConnection
        value: Host=ep-calm-poetry-adpqicy6-pooler.c-2.us-east-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_TiHxNGv3a1hX;Port=5432;SSL Mode=Require;Trust Server Certificate=true

